version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "markotsymbaluk"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
    commit-message:
      prefix: "dependabot"
  - package-ecosystem: "maven"
    directory: "/backend" # Location of pom.xml
    schedule:
      interval: "daily"
    assignees:
      - "markotsymbaluk"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "dependabot"
